<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="2" failed="1" skipped="1">
  <reporter-output>
    <line>
      <![CDATA[Take screenshot]]>
    </line>
    <line>
      <![CDATA[TC1 is running ]]>
    </line>
    <line>
      <![CDATA[Tst passed successfuly]]>
    </line>
    <line>
      <![CDATA[TC2 is running ]]>
    </line>
    <line>
      <![CDATA[Tst passed successfuly]]>
    </line>
    <line>
      <![CDATA[This test is skipped]]>
    </line>
  </reporter-output>
  <suite started-at="2022-07-04T12:20:40 IST" name="Default suite" finished-at="2022-07-04T12:20:40 IST" duration-ms="396">
    <groups>
    </groups>
    <test started-at="2022-07-04T12:20:40 IST" name="Default test" finished-at="2022-07-04T12:20:40 IST" duration-ms="396">
      <class name="listenerStudy.myTest">
        <test-method signature="TC3()[pri:0, instance:listenerStudy.myTest@2f217633]" started-at="2022-07-04T12:20:40 IST" name="TC3" finished-at="2022-07-04T12:20:40 IST" duration-ms="28" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at listenerStudy.myTest.TC3(myTest.java:26)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Take screenshot]]>
            </line>
          </reporter-output>
        </test-method> <!-- TC3 -->
        <test-method signature="TC1()[pri:0, instance:listenerStudy.myTest@2f217633]" started-at="2022-07-04T12:20:40 IST" name="TC1" finished-at="2022-07-04T12:20:40 IST" duration-ms="7" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[TC1 is running ]]>
            </line>
            <line>
              <![CDATA[Tst passed successfuly]]>
            </line>
          </reporter-output>
        </test-method> <!-- TC1 -->
        <test-method signature="TC2()[pri:0, instance:listenerStudy.myTest@2f217633]" started-at="2022-07-04T12:20:40 IST" name="TC2" finished-at="2022-07-04T12:20:40 IST" duration-ms="30" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[TC2 is running ]]>
            </line>
            <line>
              <![CDATA[Tst passed successfuly]]>
            </line>
          </reporter-output>
        </test-method> <!-- TC2 -->
        <test-method signature="TC4()[pri:0, instance:listenerStudy.myTest@2f217633]" started-at="2022-07-04T12:20:40 IST" name="TC4" finished-at="2022-07-04T12:20:40 IST" depends-on-methods="listenerStudy.myTest.TC3" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method myTest.TC4()[pri:0, instance:listenerStudy.myTest@2f217633] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method myTest.TC4()[pri:0, instance:listenerStudy.myTest@2f217633] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
            <line>
              <![CDATA[This test is skipped]]>
            </line>
          </reporter-output>
        </test-method> <!-- TC4 -->
      </class> <!-- listenerStudy.myTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
